vich_uploader:
    db_driver: orm
    #Prise en charge de PHP 8
    metadata:
        type: attribute

    mappings:
        home:
            uri_prefix: /images/home
            upload_destination: '%kernel.project_dir%/public/images/home'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        livre:
            uri_prefix: /images/livre
            upload_destination: '%kernel.project_dir%/public/images/livre'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
